INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('A', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('B', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('C', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('D', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('E', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('F', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('G', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('H', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO BRANDS (`name`, `created_at`, `updated_at`) VALUES ('I', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (1,'상의', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (2,'아우터', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (3,'바지', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (4,'스니커즈', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (5,'가방', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (6,'모자', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (7,'양말', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO CATEGORIES (`id`, `name`, `created_at`, `updated_at`) VALUES (8,'액세서리', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (11200,1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (5500, 1, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (4200, 1, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9000, 1, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 1, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1700, 1, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1800, 1, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2300, 1, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (10500,2, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (5900, 2, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3800, 2, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9100, 2, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2100, 2, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 2, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 2, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2300, 2, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (10000,3, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (6200, 3, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3300, 3, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9200, 3, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2200, 3, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1900, 3, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2200, 3, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2200, 3, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (10100,4, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (5100, 4, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3000, 4, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9500, 4, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2500, 4, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1500, 4, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2400, 4, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 4, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (10700,5, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (5000, 5, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3800, 5, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9900, 5, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2300, 5, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1800, 5, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2100, 5, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2100, 5, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (11200,6, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (7200, 6, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (4000, 6, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9300, 6, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2100, 6, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1600, 6, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2300, 6, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1900, 6, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (10500,7, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (5800, 7, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3900, 7, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9000, 7, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2200, 7, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1700, 7, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2100, 7, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 7, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (10800,8, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (6300, 8, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3100, 8, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9700, 8, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2100, 8, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1600, 8, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 8, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2000, 8, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );

INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (11400,9, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (6700, 9, 2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (3200, 9, 3, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (9500, 9, 4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2400, 9, 5, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1700, 9, 6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (1700, 9, 7, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
INSERT INTO PUBLIC.PRODUCTS (PRICE, BRAND_ID, CATEGORY_ID, CREATED_AT, UPDATED_AT) VALUES (2400, 9, 8, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP );
